first pass at chaintree
icarusz/tupelo-docs pull request #3
Opened 2019-01-23 11:35 UTC by tobowers

my first pass at: https://trello.com/c/ZddikcSV/83-write-a-chain-tree-overview-for-developers

I think it could use a little bit more of a how-to at the end... but I also wanted to just start with the data structure.

2019-01-23 11:37 UTC, tobowers commented
BTW - those are mermaid graphs - so they are graphics and not text.

2019-01-31 08:55 UTC, tobowers commented
added more reviewers since this is a technical doc.

2019-02-04 15:22 UTC, brandonwestcott requested changes
Great overview - has just the right amount of detail. The graphs really help visualize the structure, and the one sample transaction is just enough to get a feel for how the state transforms.

A few small comments, but overall 👍

2019-02-04 15:22 UTC, brandonwestcott commented on docs/chaintree.md
> +	      "payload": {
indentation on these few lines is off

2019-02-04 15:22 UTC, brandonwestcott commented on docs/chaintree.md
> +end
Using the https://mermaidjs.github.io/mermaid-live-editor/ errors on this block - might work fine in other generator code though

2019-02-04 15:22 UTC, brandonwestcott commented on docs/chaintree.md
> +	  "path": "/my/subtree/foo",
I think this and the graph below are different. I believe `/my/subtree/foo` should create [this graph](https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoiZ3JhcGggVERcblJvb3QgLS0-IHRyZWVcblJvb3QgLS0-IENoYWluXG5zdWJncmFwaCBUcmVlXG4gIHRyZWVbXCI8c3Ryb25nPnRyZWU8L3N0cm9uZz48YnIvPjxjb2RlPntcbiAgbXk6IG15Q2lkfTwvY29kZT5cIl0gLS0-IG15dHJlZVtcIjxzdHJvbmc-bXk8L3N0cm9uZz48YnIvPjxjb2RlPntzdWJ0cmVlOiBzdWJ0cmVlQ2lkfTwvY29kZT5cIl0gXG4gICBteXRyZWUtLT4gc3VidHJlZVtcIjxzdHJvbmc-c3VidHJlZTwvc3Ryb25nPjxici8-PGNvZGU-e2ZvbzogJ2Jhcid9PC9jb2RlPlwiXVxuZW5kXG5zdWJncmFwaCBDaGFpblxuQ2hhaW4gLS0gTGF0ZXN0IC0tPiBiMVtcImJsb2NrXCJdXG5DaGFpbiAtLSBHZW5lc2lzIC0tPiBiMVxuZW5kXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ)

2019-02-06 05:09 UTC, zonotope approved these changes
This looks pretty good to me, but I have a few suggestions that I think clarify the language. You can take or leave them.

Also, should we explicitly define what a tip is here?

2019-02-06 05:09 UTC, zonotope commented on docs/chaintree.md
> +A ChainTree is a novel data structure used in Tupelo to represent objects (digital and physical).
Does "novel" get us anything here that "new" doesn't? Also, I think you can make this sentence more active.

> A ChainTree is a new data structure that represents both digital and physical objects in Tupelo.

2019-02-06 05:09 UTC, zonotope commented on docs/chaintree.md
> +A ChainTree is a [content addressable](https://en.wikipedia.org/wiki/Content-addressable_storage) data structure, meaning that the entire data structure can be represented by a single hash of the roo
I would make this sentence less passive, and lean on the definition in the link a bit more to cut down on some words.

> A ChainTree is content addressable, so a single hash of the root uniquely represents the entire data structure.

2019-02-06 05:09 UTC, zonotope commented on docs/chaintree.md
> +ChainTrees use [IPLD](https://ipld.io/) for internal node linking.
I feel like this sentence should go with the next paragraph.

2019-02-06 05:09 UTC, zonotope commented on docs/chaintree.md
> +As the name implies, a ChainTree is a combination of a blockchain and a tree for the current state. That means that at any point, a ChainTree represents both its current state and the entire history
I think you can clarify this first sentence a little. I like "represents" instead of "for" because it's more precise, and I think it might make sense to clarify the blockchain part a little more.

> A ChainTree is a combination of a tree representing the current state of an object, and a blockchain representing the previous states of that object. 

With that change, the second sentence might be redundant.

2019-02-06 05:09 UTC, zonotope commented on docs/chaintree.md
> +From [Tupelo's whitepaper](https://docs.quorumcontrol.com/docs/whitepaper.html):
I think citations that double as a brief summary of what's cited flow better

> Tupelo's whitepaper explains how ChainTrees build on IPLD:

2019-02-06 05:09 UTC, zonotope commented on docs/chaintree.md
> +This data structure is the super power behind Tupelo. It allows tupelo to reach consensus on a simple hash of the root object and only store the current root of individual objects. The relevant histo
I think you should either capitalize "tupelo" in the second sentence.

2019-02-06 05:09 UTC, zonotope commented on docs/chaintree.md
> +This data structure is the super power behind Tupelo. It allows tupelo to reach consensus on a simple hash of the root object and only store the current root of individual objects. The relevant histo
I like the first sentence of this paragraph, but I think you can clarify the language a little more starting with the second

> ... With ChainTrees Tupelo only needs to reach consensus on a simple hash instead of the full, complex structure. Furthermore, Tupelo only needs to store the current root hash of each object it models because it requires clients to supply the relevant history and state needed to validate any transactions those clients issue. Tupelo nodes use the root hash they have stored to ensure this validating state and history hasn't been altered.

2019-02-06 05:09 UTC, zonotope commented on docs/chaintree.md
> +To reiterate, the ChainTree root links (using a [CID](https://github.com/multiformats/cid), from IPLD) to a tree (which is the current state) and a chain, which is a blockchain of the transactions us
I would move this paragraph (minus the "To reiterate" part) directly after you introduce IPLD. This feels like too late to reveal that you can store arbitrary data in the tree nodes.

2019-02-06 05:09 UTC, zonotope commented on docs/chaintree.md
> +Using the set data transactions, you can set data to any part of the tree and the history of those changes is preserved in the data structure.
> ... to any part of the tree and the data structure preserves the history of those changes.

2019-02-12 08:52 UTC, tobowers commented
oops - I lost track of this one. back on it. @icarusz I'd like to merge this with just the other fixes and then circle back to how to best describe storage - I think it deserves its own entry on tupelo itself rather than in the chaintree section as the two are kinda unrelated.

2019-02-12 09:12 UTC, tobowers commented on docs/chaintree.md
> +To reiterate, the ChainTree root links (using a [CID](https://github.com/multiformats/cid), from IPLD) to a tree (which is the current state) and a chain, which is a blockchain of the transactions us
I moved it up to the top

2019-02-25 09:27 UTC, tobowers commented
ping

2019-02-25 09:40 UTC, aknuds1 commented
Nice overview!

2019-02-25 12:52 UTC, brandonwestcott approved these changes

2019-02-25 12:53 UTC, brandonwestcott commented
sorry didn't realize my review was blocking

2019-02-25 13:24 UTC, tobowers commented
I leave it to @icarusz to merge.

2019-02-26 17:02 UTC, merged